spring:
  application:
    name: Spring-Cloud-Gateway
  datasource:
    url: jdbc:mysql://localhost:3306/ncsidb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
  
    hibernate:
      ddl-auto: update
    
   
  

server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443
  
jwt:
  secret: secretkey
  
#eureka.client.service-url.default-zone=http://localhost:8761/eureka

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
  